### ISSUE TITLE
 Looks like another middleware had processed this multipart request. Or maybe you are running in a cloud serverless function

### ISSUE THREAD

**Issue by alex-dolbik** [flash-oss/graphql-upload-minimal#11]
I run `processRequest(event, null, { environment: 'lambda' });` on AWS Lambda and get following error:

`InternalError: graphql-upload-minimal couldn't find any files or JSON. Looks like another middleware had processed this multipart request. Or maybe you are running in a cloud serverless function? Then see README.md.`

No additional middlewares applied, event is what I get directly from lambda. What is wrong?

Version is `1.2.1`
I use `graphql` npm package as a server

**Comment by alex-dolbik** [comment]
Actually I figured it out. The problem was that body was encoded with base64

**Comment by koresar** [comment]
hey! Great you found it! Thanks for writing this issue though. It might help other to solve similar problems in the future.
Cheers.
