### ISSUE TITLE
TypeScript declaration files

### ISSUE THREAD

**Issue by macmillen** [flash-oss/graphql-upload-minimal#13]
Hi,
since you already defined all the types internally with JSDoc why not include them as `.d.ts` files inside the library. I could help out with that if you agree and make a PR. Another way would be to contribute to DefinitelyTyped if you don't want to include them into the library.

**Comment by sgentile** [comment]
same issue

**Comment by koresar** [comment]
@sgentile go ahead. Please contribute.

Meanwhile, I'll close this issue and will wait for a your PRs.

Cheers guys.
