### ISSUE TITLE
Always getting 'POST body missing, invalid Content-Type, or JSON object has no keys.'

### ISSUE THREAD

**Issue by cas8180** [flash-oss/graphql-upload-minimal#14]
When implementing this in an Azure function, and following the example posted by another engineer implementing within an azure function I keep getting the response above. 

```ts
const server = new ApolloServer({
  schema,
  async context(azure: { request: HttpRequest; context: azCtx }) {
    //is file upload
    if (azure.request.headers['content-type'].includes('multipart/form-data')) {
      //const body = await uploadFile(azure.context, azure.request);
      const body = await processRequest(azure.context, azure.request, { environment: 'azure' });
      console.log(body);
      azure.request.body = body;
    }

    const token = Auth.trimAuth(azure.request.headers.authorization);
    const requestIp = Auth.trimAuth(azure.request.headers['x-forwarded-for']);
    try {
      const patient = await Auth.validateToken(token);
      return new Context(azure.context, token, requestIp, patient);
    } catch {
      return new Context(azure.context, token, requestIp);
    }
  },
  formatError: (err) => {
    //Handler example for masking/hiding any global output
    // Don't give the specific errors to the client.
    if (err.message.startsWith('Database Error: ')) {
      return new Error('Internal server error');
    }
    // Otherwise return the original error. The error can also
    // be manipulated in other ways, as long as it's returned.
    return err;
  },
});

export default server.createHandler();
```
<img width="1274" alt="Altair 2021-10-31 09-06-52" src="https://user-images.githubusercontent.com/1483688/139592342-fac654e8-d8b5-40fd-a650-f36f69815707.png">

**Comment by cas8180** [comment]
Same with curl
curl http://localhost:7071/api/graphql \
  -F operations='{ "query":"mutation ($picture: Upload!) { UploadAvatar(picture: $file) }", "variables": { "file": null } }' \
  -F map='{ "0": ["variables.file"] }' \
  -F 0=@a.png

**Comment by koresar** [comment]
> following the example posted by another engineer

Our time is rather limited investigating an unknown and very specific piece of your code.

Please, write a unit test and post it here if you really need us fixing your bug.

Good you are following someone's recommendations. I'd recommend asking them for help.

**Comment by Cornstar23** [comment]
@cas8180 In the screenshot, I noticed that there are red lines under $picture and $file. I think these are supposed to match and it should say instead say:
 "mutation ($picture: Upload!) { UploadAvatar(file: $picture) }",

**Comment by vahidpourmohamad** [comment]
I have the Same Problem
4 days on one line

**Comment by koresar** [comment]
Can anyone please debug and find the root cause of the bug?
We were unable to reproduce it here.

**Comment by vahidpourmohamad** [comment]
change your server to express apollo server to solve this problem in file upload
It worked for me

**Comment by koresar** [comment]
Do you have stack trace?

**Comment by vahidpourmohamad** [comment]
My problem fortunately solved 
my fault was in query definition

**Comment by vyvc-comartek** [comment]
i have same problem

**Comment by arielsashcov** [comment]
Same problem here using Apollo Server 3. Curl is the same.

`curl --location --request POST 'http://localhost:7071/api/graphql' \
--header 'Apollo-Require-Preflight: true' \
--form 'operations="'\''{\"query\":\"mutation Mutation($file: Upload!) {\\n  singleFileUpload(file: $file)\\n}\",\"variables\":{\"file\":null}}"' \
--form 'map="{ \"0\": [\"variables.file\"] }"' \
--form '0=@"/home/username/Pictures/unnamed.png"'`

**Comment by koresar** [comment]
Can someone provide a reproducible repo/code/gist?

**Comment by koresar** [comment]
The bug could be in these two lines: https://github.com/flash-oss/graphql-upload-minimal/blob/master/public/processRequest.js#L353-L354

If someone can tell us what should be there I'd put your suggestion right away and publish the module ASAP.
For now I'd have to close this as too stale. Crowdsourcing didn't work out this time.
