### ISSUE TITLE
Multiple Files

### ISSUE THREAD

**Issue by sgentile** [flash-oss/graphql-upload-minimal#17]
previously using graphql-upload we passed multiple files:

```
@Arg('files', () => GraphQLUpload) files: any[]
```

however with this fork, I'm seeing it only resolves the first file and the remainer are left in a pending state. (I can step through and see it's just resolve in upload is called once)

**Comment by koresar** [comment]
Hi there.

This is overly low amount of information.

Would you please spend some more time and submit as much information as
possible? We need to reproduce the bug to fix it.

Cheers

**Comment by koresar** [comment]
Closing while waiting for conributions.
