### ISSUE TITLE
Hanging Uploads

### ISSUE THREAD

**Issue by j** [flash-oss/graphql-upload-minimal#19]
If my request body has an invalid mapped file, the request just hangs...

```curl
curl --request POST \
  --url http://localhost:4000/ \
  --header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \
  --form 'operations={
	"query": "mutation($input: UploadInput!) { upload(input: $input) { ok } }",
	"variables": { "input": { "files": [null] } }
}' \
  --form 'map={ "0": ["variables.input.filesz"] }' \
  --form '0=@demo.pdf'
```

The above has a typo "filesz" instead of "files".  This request hangs forever.

Tested with `graphql-upload` and it works and errors out.  It even gives me a hint to the issue:

`Variable \"$input\" got invalid value { files: [null], filesz: { resolve: [function], reject: [function], promise: {}, file: [Object] } }; Field \"filesz\" is not defined by type \"UploadInput\". Did you mean \"files\"?`

**Comment by koresar** [comment]
Not sure what's up with your code, here is the response in my system(s):

```
Variable \"$input\" got invalid value { files: [null], filesz: { resolve: [function], reject: [function], promise: {}, file: [Object] } }; Field \"filesz\" is not defined by type \"UploadInput\". Did you mean \"files\"?
```

I'm pretty sure it's something wrong with your middleware or other code.

Please, submit a reproducible project and create a new ticket with more precise error if possible.
