### ISSUE TITLE
Getting a socket hang up error when trying to upload images with NestJS

### ISSUE THREAD

**Issue by forrestwilkins** [flash-oss/graphql-upload-minimal#32]
I'm using NestJS and TypeORM and am currently getting a socket hang up error whenever I try to upload an image. The operation goes through successfully when passing only text fields, but I get the error below as soon as I attempt to upload images.

The error message on the FE initially showed as the following:

```
ServerParseError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

After some digging through the network tab in Chrome, I found the socket hang up error:
```
{
  "props": { "pageProps": { "statusCode": 500 } },
  "page": "/_error",
  "query": { "__NEXT_PAGE": "/api/graphql" },
  "buildId": "development",
  "isFallback": false,
  "err": {
    "name": "Error",
    "source": "server",
    "message": "socket hang up",
    "stack": "Error: socket hang up\n at connResetException (node:internal/errors:691:14)\n    at Socket.socketCloseListener (node:_http_client:420:25)\n    at Socket.emit (node:events:402:35)\n    at TCP.\u003canonymous\u003e (node:net:687:12)"
  },
  "gip": true,
  "scriptLoader": []
}
```

The mutation I'm currently attempting to upload images with is `createPost`, and I can see through debugging that the image file is making it to the BE, and that the file is even saved partially, albeit with half of the image missing.

For my FE application, I'm using Next.js, Apollo Client, and apollo-upload-client.

I've followed the instructions from NestJS documentation for adding [custom scalars](https://docs.nestjs.com/graphql/scalars#import-a-custom-scalar) and have also tried the method detailed [here](https://vortac.io/2020/05/09/uploading-files-with-nestjs-and-graphql/) with no success.

Repos to reproduce with:
FE: https://github.com/forrestwilkins/social-ui/tree/graphql-image-uploads
BE: https://github.com/forrestwilkins/social-api/tree/graphql-image-uploads

Lastly, thank you for creating this fork. I really appreciate your efforts here!

**Comment by forrestwilkins** [comment]
@koresar Any idea what could be going wrong here, or is there anything I could do to better clarify what my issue is?

**Comment by koresar** [comment]
Hello my friend

I took a look at this.
1. The backend does not start (can't connect to the DB).
2. You would need to debug (as in JS step-by-step debugging) who is parsing your HTTP request. Most like Nest is changing your HTTP request.

From our docs:
> make sure there is no other middleware which parses **multipart/form-data** HTTP requests before the `graphqlUploadExpress` middleware!

Having 10 years of Node.js experience I would like to give you the advice (you won't follow, but that's okay).

You are using **huge enterprise framework** - Nest - as the backend for your ultra minimalistic needs.
It has multiple REST endpoints, but you are using GraphQL... You either should use REST of GraphQL. Not both.
Also, I think you have confused REST and GraphQL in your setup. Maybe even your browser UI sends REST to GraphQL!

To continue using `graphql-upload-minimal` you need to use GraphQL. Thus you don't need REST. I'd recommend replacing Next with something simpler, like `connect` or `micro` or else.
But to continue using REST you would need to abandon REST and `graphql-upload-minimal` module as well.

=====

I would like to take my privilege and close this issue as no relevant. Please, ask it on the https://stackoverflow.com/
