### ISSUE TITLE
Work with AWS Lambda but image broken, only text file can read

### ISSUE THREAD

**Issue by danniejpt** [flash-oss/graphql-upload-minimal#33]
Im not sure what is the problem 
but when I tried to open files on notepad ++
and here is the diff
1. Origin file: 
![image](https://user-images.githubusercontent.com/5358050/189315479-1502526f-9549-4c2b-8bdf-31fba787d8cf.png)

2. Uploaded file: 
![image](https://user-images.githubusercontent.com/5358050/189315542-73737f7f-84ee-4022-b6bb-bb91f5e5b5c9.png)

Anyone know why?
Here is my code: 
![image](https://user-images.githubusercontent.com/5358050/189315633-0132d59e-ffcb-4e67-b2c3-27bb140d4f1d.png)

**Comment by koresar** [comment]
This is tricky as AWS Gateway might be changing your HTTP request to something unexpected. I can't debut your specific setup. Could you please try understanding yourself who is mangling with your bytes?

Feel free to comment on this ticket. If you find that this module requires changes - please do a Pull Request. I'm closing this for now.

Chees mate.
