### ISSUE TITLE
Production mode still requires koa

### ISSUE THREAD

**Issue by pphunor72** [flash-oss/graphql-upload-minimal#36]
According to index.d.ts koa is always imported even if i want to use the package with express. Koa is listed in devDependencies so the problem affects production mode only.

**Comment by koresar** [comment]
This is the same issue going over and over again. :) We've been though it like 4 times already. You wanna fix it for everyone? PRs are welcome.
Just make sure:
* Any of the frameworks are not in "dependencies".
* TS works for both Koa and Express users.

**Comment by pphunor72** [comment]
I think publishing the code into three scoped packages (@graphql-upload-minimal/core, @graphql-upload-minimal/express, @graphql-upload-minimal/koa) would be a proper solution. Some packages I use (nestjs, mikro-orm) follow this pattern. However I am neither experienced nor skilled enough to undertake such a refactoring.

**Comment by koresar** [comment]
I'm stating to dislike TypeScript because of workload it's causing on me.

I'm happy to split this module into few parts as you suggest, but only if you do it. :) I have no time. Sorry.
