### ISSUE TITLE
Multi-file upload

### ISSUE THREAD

**Issue by short-chris** [flash-oss/graphql-upload-minimal#43]
First of all, thank you for putting out this package, its a great alternative to the original (non-minimal) one.

I am using this with NestJS, we migrated away from the jaydenseric's recently. Single uploads work fine but there is an issue with multiple. I saw your mention of fieldName in the README, which we are passing.

Here is my browser's network request:

```
operations: {"query":"mutation ExampleMutation(\n  $input: ExampleMutationInput!\n) {\n  ExampleMutation(exampleMutationInput: $input) {\n    createdAt\n  }\n}\n","variables":{"input":{"files":[null,null,null],"price":0,}}}
map: {"FILE_1":["variables.input.files.0"],"FILE_2":["variables.input.files.1"],"FILE_3":["variables.input.files.2"]}
FILE_1: (binary)
FILE_2: (binary)
FILE_3: (binary)
```

and here is what it looks like in Nest/Node when I try to access the uploaded files:

```js
[
  Promise {
    {
      fieldName: 'FILE_1',
      filename: 'FILE_Screenshot 2023-03-25 at 4.20.11 PM.png',
      mimetype: 'image/png',
      encoding: '7bit',
      createReadStream: [Function: createReadStream]
    },
    [Symbol(async_id_symbol)]: 2581,
    [Symbol(trigger_async_id_symbol)]: 2572,
    [Symbol(kResourceStore)]: I18nContext { lang: 'en', service: [I18nService], id: 1 }
  },
  Promise {
    <pending>,
    [Symbol(async_id_symbol)]: 2584,
    [Symbol(trigger_async_id_symbol)]: 2572,
    [Symbol(kResourceStore)]: I18nContext { lang: 'en', service: [I18nService], id: 1 }
  },
  Promise {
    <pending>,
    [Symbol(async_id_symbol)]: 2587,
    [Symbol(trigger_async_id_symbol)]: 2572,
    [Symbol(kResourceStore)]: I18nContext { lang: 'en', service: [I18nService], id: 1 }
  }
]
```

If I try to `Promise.all()` that array it just hangs. If I try to await the second (1) file, it just hangs. The first one works. Im at a loss as to what else to do here. Am I sending this to my server wrong from the browser?

Thanks for any help!

**Comment by koresar** [comment]
Hello.

We have multi-file uploads every day (with express.js). All works just fine.

Your debugging info look absolutely correct and expected.

Your resolver should await files one by one. Never skip the first one. If you do not consume the first file, the browser won't send you the second. You should do this:

```js
        for (const file of files) {
          const { createReadStream, filename /*, fieldName, mimetype, encoding */ } = await file.file;
          createReadStream().pipe( to your destination and WAIT FOR IT TO FINISH before consuming the second file );
        }
```

**Comment by Cauen** [comment]
Hi @koresar 
There is an example fore multiple file upload using that lib?

I was unable to workaround this problem, the second 'await' never ends and the file.file does not exist
Meanwhile I stayed at https://www.npmjs.com/package/graphql-upload-ts

**Comment by koresar** [comment]
@Cauen your issue is different to the OP.

This is how your code should look like:
https://github.com/flash-oss/graphql-upload-minimal?tab=readme-ov-file#expressjs
