### ISSUE TITLE
Uploading multiple files, only one file appears properly all other files coming as promise pending.

### ISSUE THREAD

**Issue by qalbit** [flash-oss/graphql-upload-minimal#45]
I am using graphql-upload-minimal and getting this error while uploading multiple files.
Some Uploads are coming as promise pending only first file appears properly.

Upload {
    resolve: [Function (anonymous)],
    reject: [Function (anonymous)],
    promise: Promise { [Object] },
    file: {
      fieldName: '0',
      filename: 'stock-photo.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      createReadStream: [Function: createReadStream]
    }
  },
  Upload {
    resolve: [Function (anonymous)],
    reject: [Function (anonymous)],
    promise: Promise { <pending> }
  },
  Upload {
    resolve: [Function (anonymous)],
    reject: [Function (anonymous)],
    promise: Promise { <pending> }
  },
  Upload {
    resolve: [Function (anonymous)],
    reject: [Function (anonymous)],
    promise: Promise { <pending> }
  }
  
  
  Please check this issue and get back to me ASAP.

**Comment by koresar** [comment]
Not enough info. Please see the README examples.

**Comment by ajithv11** [comment]
I am also struck with the same issue. Form data is sending correctly

![image](https://github.com/flash-oss/graphql-upload-minimal/assets/22443417/35b482b7-eb0c-43d1-ac12-b621874b8b99)

Mutation code is given below

    mutation multipleUpload($file : [Upload]!){
      multipleUpload(  
        file : $file,
        name: "This is a test"
        
      ){
        message
      }
    }

Resolver code is given below

    multipleUpload : async (args, contextValue) => {
        console.log(args.file);
        return {
            message: "File Uploaded"
        }
    }

Console log of file gives only a single value , See screenshot below

![image](https://github.com/flash-oss/graphql-upload-minimal/assets/22443417/ed35c568-5233-42e2-9bd8-7b9edc126f17)
