### ISSUE TITLE
Multiple file upload is showing as single array with promise, How to itreate and capture all file here

### ISSUE THREAD

**Issue by ajithv11** [flash-oss/graphql-upload-minimal#47]
I am also struck with the same issue. Form data is sending correctly

![image](https://github.com/flash-oss/graphql-upload-minimal/assets/22443417/35b482b7-eb0c-43d1-ac12-b621874b8b99)

Mutation code is given below

    mutation multipleUpload($file : [Upload]!){
      multipleUpload(  
        file : $file,
        name: "This is a test"
        
      ){
        message
      }
    }

Resolver code is given below

    multipleUpload : async (args, contextValue) => {
        console.log(args.file);
        return {
            message: "File Uploaded"
        }
    }

Console log of file gives only a single value , See screenshot below

![image](https://github.com/flash-oss/graphql-upload-minimal/assets/22443417/ed35c568-5233-42e2-9bd8-7b9edc126f17)

Also if I running the upload 2nd time, It goes to a waiting stage , So I guess I didn't complete the promise

**Comment by koresar** [comment]
Thanks for much info. I assume there could be a bug when the `Upload` is in an array: `[Upload]`.
Any chance you can give me a minimal reproducible code? So that I can run and debug on my computer.

**Comment by ajithv11** [comment]
[multiUpload.zip](https://github.com/flash-oss/graphql-upload-minimal/files/15245017/multiUpload.zip)
@koresar  I have attached a minimal code with multi upload option, Could you please check

**Comment by ajithv11** [comment]
@koresar  Any update on this

**Comment by koresar** [comment]
Thanks for the reminder.
I’m currently super busy. Is it okay if I look at this tomorrow?

**Comment by ajithv11** [comment]
@koresar  Sure Thank you!

**Comment by ajithv11** [comment]
@koresar Any update?

**Comment by koresar** [comment]
Hi @ajithv11 
Thanks for the file. I was able to run the server. However, I couldn't figure out what HTTP request to do in order to trigger the bug.
Could you please provide a full `curl` command?

**Comment by koresar** [comment]
Hello. There was no update on this issue for 6 weeks. So closing it now. Feel free to reopen.
