### ISSUE TITLE
createReadStream is not a function

### ISSUE THREAD

**Issue by cupmen4800** [flash-oss/graphql-upload-minimal#48]
## Assumptions
The following packages are used
- nodejs 18.18.0
- graphql-upload-minimal 1.6.1
- @nestjs/graphql 12.1.0

It shows **"createReadStream is not a function."** Sorry if I have used it incorrectly.

## Code
This is a partial excerpt from the entire code.
```ts
  async uploadFile(filePath: string, bucketName: string, file: FileUpload): Promise<string> {
    const bucket = this.storage.bucket(bucketName);
    const blob = bucket.file(filePath);

    try {
      const { createReadStream, mimetype } = file;
      const blobStream = blob.createWriteStream({
        metadata: {
          contentType: mimetype,
        },
        public: true,
      });
      const fileStream = createReadStream();

      await pipeline(fileStream, blobStream);

      await blob.makePublic();

      const publicUrl =
        process.env.NODE_ENV === 'development'
          ? `${process.env.STORAGE_EMULATOR_HOST}/storage/v1/b/${bucketName}/${filePath}`
          : `https://storage.googleapis.com/storage/v1/b/${bucketName}/${filePath}`;

      return publicUrl;
    } catch (error) {
      throw new Error(`File upload failed: ${error.message}`);
    }
  }
```

Sorry if there are any poor parts as I am using Deepl translation.

**Comment by koresar** [comment]
Looks like you need to `await` the `file`. See example in readme:

```js
const { createReadStream, filename /*, fieldName, mimetype, encoding */ } = await doc.file;
```

**Comment by cupmen4800** [comment]
Resolved🙏
We did not try this because this is what was displayed.
"'await' has no effect on the type of this expression.ts(80007)"

**Comment by koresar** [comment]
yeah, because you need to await the `file` before passing to your `uploadFile()` function.

I'd recommend the  `uploadFile()` to accept `mimeType` and `readableStream` instead of `file`.
