### ISSUE TITLE
fastify support 

### ISSUE THREAD

**Issue by vinkovsky** [flash-oss/graphql-upload-minimal#50]

**Comment by koresar** [comment]
Great idea! Can you please submit a PR? You'd ned to add, like, 15 lines of code. See example here: https://github.com/flash-oss/graphql-upload-minimal/blob/master/public/graphqlUploadExpress.js

**Comment by vinkovsky** [comment]
@koresar yes, of course! I'll try to do it this week

**Comment by WKampel** [comment]
It works in fastify for me, except for react native files (only works on web)
