### ISSUE TITLE
Azure: Larger binary file seems to be twice the size and is corrupted

### ISSUE THREAD

**Issue by derSchtefan** [flash-oss/graphql-upload-minimal#9]
When running in an Azure Function context, the file stream is suddenly approximately twice the size, and the binary data is corrupted. It appears that at the end of the file, the binary data is repeated, but not exactly twice.

Only happens with Azure.

**Comment by koresar** [comment]
Thank you for reporting!
None of us have access to the Azure functions. Do you have an opportunity
to fix this bug for us in a PR?

**Comment by derSchtefan** [comment]
@koresar I can **try**, I am not sure I will be able to find the bug though. 

But FYI: The problem already happens when testing the function locally, and the Azure function host is free to download, and even automatically gets installed when you create a new "TypeScript" Azure Function via VS Code (Azure Functions Extension). You can then simply run and debug locally.  You can also install it manually .

https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2#typescript

**Comment by derSchtefan** [comment]
Ah, I think I found it. I think the issue is that you are assuming the binary request body in Auzre is in req.rawBody, while binary data will be actually in req.body  (and the binding needs to be set to binary).

See here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2#bindings-data-type

Another example of a person using Busboy to parse multipart form data in Azure Functions with node confirms it:
https://www.sergevandenoever.nl/Processing-multipart-form-data-in-nodejs-azure-function-with-httptrigger/

**Comment by derSchtefan** [comment]
@koresar Fixed in PR #10

**Comment by koresar** [comment]
Published as v1.2.1
Thank you @derSchtefan . You are magnificent!
